"""Opt-in composition and generated-file ownership (standard library only).

Format implementations run in a separate UV script; ordinary deployment never
imports a TOML library or needs UV. Generated bytes and their checksums live in
local state, not in the repository.
"""
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile


class CompositionError(Exception):
    pass


FORMATS = {"toml"}
PLATFORMS = ("macos", "omarchy", "ubuntu")


def merge_target(relative):
    match = re.fullmatch(r"(.+)\.merge\.([^.]+)", relative.name)
    if match:
        return relative.with_name(match[1] + "." + match[2]), match[2]
    return None


def digest(content):
    return hashlib.sha256(content).hexdigest()


def safe_path(path):
    """State files must never be accessed through symlinks, including ancestors."""
    for parent in [*reversed(path.parents), path]:
        if parent.is_symlink():
            raise CompositionError(f"Symlink in generated storage: {parent}")
        if parent != path and parent.exists() and not parent.is_dir():
            raise CompositionError(f"Not a regular generated directory: {parent}")
    if path.exists() and not path.is_file():
        raise CompositionError(f"Not a regular generated file: {path}")


def atomic_write(path, content):
    safe_path(path)
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".dot-", dir=str(path.parent))
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def render(root, home, requests):
    """Batch all compositions into one format-helper invocation; write nothing."""
    if not requests:
        return []
    uv = shutil.which("uv")
    if not uv:
        local = home / ".local/bin/uv"
        if local.is_file() and os.access(local, os.X_OK):
            uv = str(local)
    if not uv:
        raise CompositionError("UV is required to merge TOML; run dot install or install uv.")
    result = subprocess.run(
        [uv, "run", "--quiet", "--no-project", "--script", str(root / "lib/merge_config.py")],
        input=json.dumps(requests), capture_output=True, text=True,
    )
    if result.returncode:
        raise CompositionError("Configuration merge failed: " + result.stderr.strip())
    outputs = json.loads(result.stdout)
    if not isinstance(outputs, list) or len(outputs) != len(requests) or not all(isinstance(s, str) for s in outputs):
        raise CompositionError("Invalid response from configuration merge helper.")
    header = "# Generated by dot. Edit the global config or platform merge file, then redeploy.\n"
    return [(header + text).encode("utf-8") for text in outputs]


class GeneratedStore:
    def __init__(self, root, home, platform):
        state = Path(os.environ.get("XDG_STATE_HOME") or home / ".local/state")
        self.root = root
        self.home = home
        # XDG's root is user-selected and may itself be a symlink (e.g. /tmp
        # on macOS). Resolve it once; guard every path beneath it separately.
        self.state = state.resolve() if state.is_absolute() else state
        self.base = self.state / "dot/generated" / digest(str(root).encode())[:16]
        self.platform = platform
        self._records = {}

    def validate_location(self):
        if not self.state.is_absolute():
            raise CompositionError("XDG_STATE_HOME must be an absolute path.")
        if self.base == self.root or self.root in self.base.parents:
            raise CompositionError("Generated storage must be outside the repository.")
        # Validate ancestors even when the metadata/output does not exist yet.
        safe_path(self.base / "placeholder")

    def metadata(self, platform):
        return self.base / (platform + ".json")

    def records(self, platform=None):
        platform = platform or self.platform
        if platform not in self._records:
            self.validate_location()
            path = self.metadata(platform)
            safe_path(path)
            records = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
            if not isinstance(records, dict):
                raise CompositionError(f"Invalid generated metadata: {path}")
            for name, checksum in records.items():
                relative = Path(name)
                if (not name or relative.is_absolute() or any(p in ("", ".", "..") for p in name.split("/"))
                        or not isinstance(checksum, str) or not re.fullmatch(r"[0-9a-f]{64}", checksum)):
                    raise CompositionError(f"Invalid generated metadata: {path}")
                target = self.home / relative
                for protected in (self.root, self.base):
                    if target == protected or protected in target.parents or target in protected.parents:
                        raise CompositionError(f"Generated destination overlaps protected storage: {target}")
            self._records[platform] = records
        return self._records[platform]

    def output(self, relative, platform=None):
        return self.base / (platform or self.platform) / relative

    def registered(self, path):
        """Recognize only exact recorded output paths, never arbitrary state links."""
        try:
            relative = path.relative_to(self.base)
        except ValueError:
            return False
        if len(relative.parts) < 2 or relative.parts[0] not in PLATFORMS:
            return False
        platform, name = relative.parts[0], Path(*relative.parts[1:]).as_posix()
        if name not in self.records(platform):
            return False
        safe_path(path)
        return True

    def modified(self, path):
        if not self.registered(path) or not path.exists():
            return False
        relative = path.relative_to(self.base)
        checksum = self.records(relative.parts[0])[Path(*relative.parts[1:]).as_posix()]
        return digest(path.read_bytes()) != checksum

    def output_conflict(self, relative):
        """Also protect retained output when its HOME link has been removed."""
        self.records()
        path = self.output(relative)
        safe_path(path)
        return path.exists() and (not self.registered(path) or self.modified(path))

    def write(self, relative, content):
        path = self.output(relative)
        records = self.records()
        safe_path(path)
        if not path.exists() or path.read_bytes() != content:
            atomic_write(path, content)
        records[relative.as_posix()] = digest(content)
        atomic_write(self.metadata(self.platform), (json.dumps(records, indent=2) + "\n").encode())
