alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ollama='ollama.exe'
alias mach_list_systemctl='systemctl list-unit-files --state=enabled'
alias free='free -m'
